import test from "node:test";
import assert from "node:assert/strict";
import * as numbers from "../src/numbers.js";

test("isNumber", () => {
  assert.equal(numbers.isNumber(10), true);
  assert.equal(numbers.isNumber(10.5), true);
  assert.equal(numbers.isNumber(-3), true);
  assert.equal(numbers.isNumber(-0), true);
  assert.equal(numbers.isNumber("10"), false);
  assert.equal(numbers.isNumber(null), false);
  assert.equal(numbers.isNumber(undefined), false);
  assert.equal(numbers.isNumber(true), false);
  assert.equal(numbers.isNumber(NaN), false);
  assert.equal(numbers.isNumber(Infinity), false);
  assert.equal(numbers.isNumber(-Infinity), false);
});

test("isInteger", () => {
  assert.equal(numbers.isInteger(10), true);
  assert.equal(numbers.isInteger(-3), true);
  assert.equal(numbers.isInteger(0), true);
  assert.equal(numbers.isInteger(-0), true);
  assert.equal(numbers.isInteger(10.5), false);
  assert.equal(numbers.isInteger("10"), false);
  assert.equal(numbers.isInteger(null), false);
  assert.equal(numbers.isInteger(true), false);
  assert.equal(numbers.isInteger(NaN), false);
  assert.equal(numbers.isInteger(Infinity), false);
  assert.equal(numbers.isInteger(-Infinity), false);
});

test("isPositive", () => {
  assert.equal(numbers.isPositive(10), true);
  assert.equal(numbers.isPositive(0.5), true);
  assert.equal(numbers.isPositive(0), false);
  assert.equal(numbers.isPositive(-0), false);
  assert.equal(numbers.isPositive(-3), false);
  assert.equal(numbers.isPositive("10"), false);
  assert.equal(numbers.isPositive(null), false);
  assert.equal(numbers.isPositive(NaN), false);
  assert.equal(numbers.isPositive(Infinity), false);
  assert.equal(numbers.isPositive(-Infinity), false);
});

test("isNegative", () => {
  assert.equal(numbers.isNegative(-10), true);
  assert.equal(numbers.isNegative(-0.5), true);
  assert.equal(numbers.isNegative(0), false);
  assert.equal(numbers.isNegative(-0), false);
  assert.equal(numbers.isNegative(3), false);
  assert.equal(numbers.isNegative("-10"), false);
  assert.equal(numbers.isNegative(null), false);
  assert.equal(numbers.isNegative(NaN), false);
  assert.equal(numbers.isNegative(Infinity), false);
  assert.equal(numbers.isNegative(-Infinity), false);
});

test("isEven", () => {
  assert.equal(numbers.isEven(10), true);
  assert.equal(numbers.isEven(0), true);
  assert.equal(numbers.isEven(-0), true);
  assert.equal(numbers.isEven(-4), true);
  assert.equal(numbers.isEven(7), false);
  assert.equal(numbers.isEven(-3), false);
  assert.equal(numbers.isEven(2.5), false);
  assert.equal(numbers.isEven("10"), false);
  assert.equal(numbers.isEven(null), false);
  assert.equal(numbers.isEven(NaN), false);
  assert.equal(numbers.isEven(Infinity), false);
});

test("isOdd", () => {
  assert.equal(numbers.isOdd(7), true);
  assert.equal(numbers.isOdd(-3), true);
  assert.equal(numbers.isOdd(0), false);
  assert.equal(numbers.isOdd(-0), false);
  assert.equal(numbers.isOdd(10), false);
  assert.equal(numbers.isOdd(-4), false);
  assert.equal(numbers.isOdd(2.5), false);
  assert.equal(numbers.isOdd("7"), false);
  assert.equal(numbers.isOdd(null), false);
  assert.equal(numbers.isOdd(NaN), false);
  assert.equal(numbers.isOdd(Infinity), false);
});

test("toNumber", () => {
  assert.equal(numbers.toNumber(10, 0), 10);
  assert.equal(numbers.toNumber(-3.5, 0), -3.5);
  assert.equal(numbers.toNumber(0, 99), 0);
  assert.equal(numbers.toNumber(1, 99), 1);
  assert.equal(numbers.toNumber("42", 0), 42);
  assert.equal(numbers.toNumber(" 4.5 ", 0), 4.5);
  assert.equal(numbers.toNumber("0", 99), 0);
  assert.equal(numbers.toNumber("0.0", 99), 0);
  assert.equal(numbers.toNumber("1", 99), 1);
  assert.equal(numbers.toNumber("1.0", 99), 1);
  assert.equal(numbers.toNumber("0x10", 99), 16);
  assert.equal(numbers.toNumber("1e3", 99), 1000);
  assert.equal(numbers.toNumber("+12", 99), 12);
  assert.equal(numbers.toNumber("-0.5", 99), -0.5);
  assert.equal(numbers.toNumber("", 99), 99);
  assert.equal(numbers.toNumber("   ", 99), 99);
  assert.equal(numbers.toNumber("12abc", 99), 99);
  assert.equal(numbers.toNumber(null, 99), 99);
  assert.equal(numbers.toNumber(undefined, 99), 99);
  assert.equal(numbers.toNumber(true, 99), 99);
  assert.equal(numbers.toNumber(false, 99), 99);
  assert.equal(numbers.toNumber([], 99), 99);
  assert.equal(numbers.toNumber(["42"], 99), 99);
  assert.equal(numbers.toNumber({}, 99), 99);
  assert.equal(numbers.toNumber(NaN, 99), 99);
  assert.equal(numbers.toNumber(Infinity, 99), 99);
  assert.equal(numbers.toNumber(-Infinity, 99), 99);
  assert.equal(numbers.toNumber("Infinity", 99), 99);
  assert.equal(numbers.toNumber("-Infinity", 99), 99);
  assert.equal(numbers.toNumber(10n, 99), 99);
  assert.equal(numbers.toNumber(Symbol("10"), 99), 99);
  assert.equal(numbers.toNumber("abc", null), null);
  assert.equal(numbers.toNumber("abc", "invalid"), "invalid");
});

test("clamp", () => {
  assert.equal(numbers.clamp(5, 1, 10), 5);
  assert.equal(numbers.clamp(0, -5, 5), 0);
  assert.equal(numbers.clamp(1.5, 1, 2), 1.5);
  assert.equal(numbers.clamp(1, 1, 10), 1);
  assert.equal(numbers.clamp(10, 1, 10), 10);
  assert.equal(numbers.clamp(0, 1, 10), 1);
  assert.equal(numbers.clamp(-10, -5, 5), -5);
  assert.equal(numbers.clamp(12, 1, 10), 10);
  assert.equal(numbers.clamp(8, -5, 5), 5);
  assert.equal(Number.isNaN(numbers.clamp("5", 1, 10)), true);
  assert.equal(Number.isNaN(numbers.clamp(NaN, 1, 10)), true);
  assert.equal(Number.isNaN(numbers.clamp(Infinity, 1, 10)), true);
  assert.equal(Number.isNaN(numbers.clamp(5, "1", 10)), true);
  assert.equal(Number.isNaN(numbers.clamp(5, 1, null)), true);
  assert.equal(Number.isNaN(numbers.clamp(5, 10, 1)), true);
});

test("roundTo", () => {
  assert.equal(numbers.roundTo(10.5678, 2), 10.57);
  assert.equal(numbers.roundTo(10.5623, 2), 10.56);
  assert.equal(numbers.roundTo(-2.456, 2), -2.46);
  assert.equal(numbers.roundTo(10.5678, 0), 11);
  assert.equal(numbers.roundTo(10.4, 0), 10);
  assert.equal(numbers.roundTo(-2.6, 0), -3);
  assert.equal(numbers.roundTo(5.5, 3), 5.5);
  assert.equal(numbers.roundTo(0, 2), 0);
  assert.equal(Number.isNaN(numbers.roundTo("abc", 2)), true);
  assert.equal(Number.isNaN(numbers.roundTo("1.25", 1)), true);
  assert.equal(Number.isNaN(numbers.roundTo(null, 2)), true);
  assert.equal(Number.isNaN(numbers.roundTo(true, 2)), true);
  assert.equal(Number.isNaN(numbers.roundTo(undefined, 2)), true);
  assert.equal(Number.isNaN(numbers.roundTo(NaN, 2)), true);
  assert.equal(Number.isNaN(numbers.roundTo(Infinity, 2)), true);
  assert.equal(Number.isNaN(numbers.roundTo(-Infinity, 2)), true);
  assert.equal(Number.isNaN(numbers.roundTo(1.25, -1)), true);
  assert.equal(Number.isNaN(numbers.roundTo(1.25, 101)), true);
  assert.equal(Number.isNaN(numbers.roundTo(1.25, 1.5)), true);
  assert.equal(Number.isNaN(numbers.roundTo(1.25, "2")), true);
  assert.equal(Number.isNaN(numbers.roundTo(1.25, undefined)), true);
  //assert.equal(numbers.roundTo(1.005, 2), 1.01);
});

test("percentage", () => {
  assert.equal(numbers.percentage(25, 100), 25);
  assert.equal(numbers.percentage(5, 20), 25);
  assert.equal(numbers.percentage(1, 3), 33.33333333333333);
  assert.equal(numbers.percentage(0, 50), 0);
  assert.equal(numbers.percentage(150, 100), 150);
  assert.equal(numbers.percentage(30, 20), 150);
  assert.equal(numbers.percentage(-25, 100), -25);
  assert.equal(numbers.percentage(25, -100), -25);
  assert.equal(numbers.percentage(-25, -100), 25);
  assert.equal(numbers.percentage(10, 0), 0); 
  assert.equal(numbers.percentage(0, 0), 0);
  assert.equal(Number.isNaN(numbers.percentage("abc", 100)), true);
  assert.equal(Number.isNaN(numbers.percentage(25, "xyz")), true);
  assert.equal(Number.isNaN(numbers.percentage(undefined, 100)), true);
  assert.equal(Number.isNaN(numbers.percentage(25, null)), true);
  assert.equal(Number.isNaN(numbers.percentage(NaN, 100)), true);
  assert.equal(Number.isNaN(numbers.percentage(Infinity, 100)), true);
  assert.equal(Number.isNaN(numbers.percentage(25, Infinity)), true);
  assert.equal(Number.isNaN(numbers.percentage(-Infinity, 100)), true);
  assert.equal(Number.isNaN(numbers.percentage(true, 100)), true);
  assert.equal(Number.isNaN(numbers.percentage(25, false)), true);
});

test("sum", () => {
  assert.equal(numbers.sum([1, 2, 3, 4]), 10);
  assert.equal(numbers.sum([-1, -2, 3]), 0);
  assert.equal(numbers.sum([1.5, 2.5]), 4);
  assert.equal(Number.isNaN(numbers.sum([])), true);
  assert.equal(Number.isNaN(numbers.sum([1, 2, "abc", 4])), true);
  assert.equal(Number.isNaN(numbers.sum([1, undefined, 3])), true);
  assert.equal(Number.isNaN(numbers.sum([1, NaN, 3])), true);
  assert.equal(Number.isNaN(numbers.sum([1, null, 3])), true);
  assert.equal(Number.isNaN(numbers.sum([1, Infinity, 3])), true);
  assert.equal(Number.isNaN(numbers.sum([1, -Infinity, 3])), true);
  assert.equal(Number.isNaN(numbers.sum([1, "2", 3])), true);
  assert.equal(Number.isNaN(numbers.sum([1, true, 3])), true);
  assert.equal(Number.isNaN(numbers.sum([1, {}, 3])), true);
  assert.equal(Number.isNaN(numbers.sum(null)), true);
  assert.equal(Number.isNaN(numbers.sum(undefined)), true);
  assert.equal(Number.isNaN(numbers.sum("123")), true);
  assert.equal(Number.isNaN(numbers.sum({})), true);
  assert.equal(Number.isNaN(numbers.sum({ value: 1 })), true);
  //assert.equal(Number.isNaN(numbers.sum([, 1])), true);
  assert.equal(Number.isNaN(numbers.sum([1, Symbol("2"), 3])), true);
});

test("average", () => {
  assert.equal(numbers.average([1, 2, 3, 4]), 2.5);
  assert.equal(numbers.average([-1, -2, 3]), 0);
  assert.equal(numbers.average([1.5, 2.5]), 2);
  assert.equal(numbers.average([0]), 0);
  assert.equal(numbers.average([5]), 5);
  assert.equal(Number.isNaN(numbers.average([])), true);
  assert.equal(Number.isNaN(numbers.average([1, "2", 3])), true);
  assert.equal(Number.isNaN(numbers.average([1, null, 3])), true);
  assert.equal(Number.isNaN(numbers.average([1, undefined, 3])), true);
  assert.equal(Number.isNaN(numbers.average([1, NaN, 3])), true);
  assert.equal(Number.isNaN(numbers.average([1, Infinity, 3])), true);
  assert.equal(Number.isNaN(numbers.average([1, -Infinity, 3])), true);
  assert.equal(Number.isNaN(numbers.average([1, true, 3])), true);
  assert.equal(Number.isNaN(numbers.average([1, {}, 3])), true);
  assert.equal(Number.isNaN(numbers.average(null)), true);
  assert.equal(Number.isNaN(numbers.average(undefined)), true);
  assert.equal(Number.isNaN(numbers.average("123")), true);
  assert.equal(Number.isNaN(numbers.average({})), true);
  assert.equal(Number.isNaN(numbers.average({ value: 1 })), true);
  //assert.equal(Number.isNaN(numbers.average([, 1])), true);
  assert.equal(Number.isNaN(numbers.average([1, Symbol("2"), 3])), true);
});

test("min", () => {
  assert.equal(numbers.min([1, 2, 3, 4]), 1);
  assert.equal(numbers.min([-1, -5, 3]), -5);
  assert.equal(numbers.min([1.5, 0.5, 2.5]), 0.5);
  assert.equal(numbers.min([0, 5, 10]), 0);
  assert.equal(numbers.min([7]), 7);
  assert.equal(numbers.min([3, 1, 1, 2]), 1);
  assert.equal(Number.isNaN(numbers.min([])), true);
  assert.equal(Number.isNaN(numbers.min([1, "2", 3])), true);
  assert.equal(Number.isNaN(numbers.min([1, null, 3])), true);
  assert.equal(Number.isNaN(numbers.min([1, undefined, 3])), true);
  assert.equal(Number.isNaN(numbers.min([1, NaN, 3])), true);
  assert.equal(Number.isNaN(numbers.min([1, Infinity, 3])), true);
  assert.equal(Number.isNaN(numbers.min([1, -Infinity, 3])), true);
  assert.equal(Number.isNaN(numbers.min([1, true, 3])), true);
  assert.equal(Number.isNaN(numbers.min([1, {}, 3])), true);
  assert.equal(Number.isNaN(numbers.min(null)), true);
  assert.equal(Number.isNaN(numbers.min(undefined)), true);
  assert.equal(Number.isNaN(numbers.min("123")), true);
  assert.equal(Number.isNaN(numbers.min({})), true);
  assert.equal(Number.isNaN(numbers.min({ value: 1 })), true);
  //assert.equal(Number.isNaN(numbers.min([, 2])), true);
  assert.equal(Number.isNaN(numbers.min([1, Symbol("2"), 3])), true);
});

test("max", () => {
  assert.equal(numbers.max([1, 2, 3, 4]), 4);
  assert.equal(numbers.max([-1, -5, 3]), 3);
  assert.equal(numbers.max([-10, -2, -7]), -2);
  assert.equal(numbers.max([1.5, 0.5, 2.5]), 2.5);
  assert.equal(numbers.max([0, 5, 10]), 10);
  assert.equal(numbers.max([7]), 7);
  assert.equal(numbers.max([3, 3, 1, 2]), 3);
  assert.equal(Number.isNaN(numbers.max([])), true);
  assert.equal(Number.isNaN(numbers.max([1, "2", 3])), true);
  assert.equal(Number.isNaN(numbers.max([1, null, 3])), true);
  assert.equal(Number.isNaN(numbers.max([1, undefined, 3])), true);
  assert.equal(Number.isNaN(numbers.max([1, NaN, 3])), true);
  assert.equal(Number.isNaN(numbers.max([1, Infinity, 3])), true);
  assert.equal(Number.isNaN(numbers.max([1, -Infinity, 3])), true);
  assert.equal(Number.isNaN(numbers.max([1, true, 3])), true);
  assert.equal(Number.isNaN(numbers.max([1, {}, 3])), true);
  assert.equal(Number.isNaN(numbers.max(null)), true);
  assert.equal(Number.isNaN(numbers.max(undefined)), true);
  assert.equal(Number.isNaN(numbers.max("123")), true);
  assert.equal(Number.isNaN(numbers.max({})), true);
  assert.equal(Number.isNaN(numbers.max({ value: 1 })), true);
  //assert.equal(Number.isNaN(numbers.max([, 2])), true);
  assert.equal(Number.isNaN(numbers.max([1, Symbol("2"), 3])), true);
});

test("product", () => {
  assert.equal(numbers.product([1, 2, 3, 4]), 24);
  assert.equal(numbers.product([-1, 2, 3]), -6);
  assert.equal(numbers.product([-2, -3, 4]), 24);
  assert.equal(numbers.product([1.5, 2]), 3);
  assert.equal(numbers.product([0, 2, 3]), 0);
  assert.equal(numbers.product([7]), 7);
  assert.equal(numbers.product([1, 1, 1]), 1);
  assert.equal(Number.isNaN(numbers.product([])), true);
  assert.equal(Number.isNaN(numbers.product([1, "2", 3])), true);
  assert.equal(Number.isNaN(numbers.product([1, null, 3])), true);
  assert.equal(Number.isNaN(numbers.product([1, undefined, 3])), true);
  assert.equal(Number.isNaN(numbers.product([1, NaN, 3])), true);
  assert.equal(Number.isNaN(numbers.product([1, Infinity, 3])), true);
  assert.equal(Number.isNaN(numbers.product([1, -Infinity, 3])), true);
  assert.equal(Number.isNaN(numbers.product([1, true, 3])), true);
  assert.equal(Number.isNaN(numbers.product([1, {}, 3])), true);
  assert.equal(Number.isNaN(numbers.product(null)), true);
  assert.equal(Number.isNaN(numbers.product(undefined)), true);
  assert.equal(Number.isNaN(numbers.product("123")), true);
  assert.equal(Number.isNaN(numbers.product({})), true);
  assert.equal(Number.isNaN(numbers.product({ value: 1 })), true);
  assert.equal(Number.isNaN(numbers.product([, 2])), true);
  assert.equal(Number.isNaN(numbers.product([1, Symbol("2"), 3])), true);
});

test("isBetween", () => {
  assert.equal(numbers.isBetween(5, 1, 10), true);
  assert.equal(numbers.isBetween(1, 1, 10), true);
  assert.equal(numbers.isBetween(10, 1, 10), true);
  assert.equal(numbers.isBetween(0, -5, 5), true);
  assert.equal(numbers.isBetween(-2.5, -3, -2), true);
  assert.equal(numbers.isBetween(0.5, 0, 1), true);
  assert.equal(numbers.isBetween(0, 1, 10), false);
  assert.equal(numbers.isBetween(11, 1, 10), false);
  assert.equal(numbers.isBetween(-6, -5, 5), false);
  assert.equal(numbers.isBetween(5, 10, 1), false);
  assert.equal(numbers.isBetween("5", 1, 10), false);
  assert.equal(numbers.isBetween(null, 1, 10), false);
  assert.equal(numbers.isBetween(undefined, 1, 10), false);
  assert.equal(numbers.isBetween(true, 1, 10), false);
  assert.equal(numbers.isBetween(NaN, 1, 10), false);
  assert.equal(numbers.isBetween(Infinity, 1, 10), false);
  assert.equal(numbers.isBetween(-Infinity, 1, 10), false);
  assert.equal(numbers.isBetween(5, "1", 10), false);
  assert.equal(numbers.isBetween(5, null, 10), false);
  assert.equal(numbers.isBetween(5, 1, undefined), false);
  assert.equal(numbers.isBetween(5, 1, Infinity), false);
});

test("isCloseTo", () => {
  assert.equal(numbers.isCloseTo(10, 10, 0), true);
  assert.equal(numbers.isCloseTo(10, 12, 2), true);
  assert.equal(numbers.isCloseTo(10, 11.5, 2), true);
  assert.equal(numbers.isCloseTo(-10, -12, 2), true);
  assert.equal(numbers.isCloseTo(0.1 + 0.2, 0.3, Number.EPSILON), true);
  assert.equal(numbers.isCloseTo(10, 12.1, 2), false);
  assert.equal(numbers.isCloseTo(-10, -12.1, 2), false);
  assert.equal(numbers.isCloseTo(10, 10.1, 0), false);
  assert.equal(numbers.isCloseTo(10, 10, -1), false);
  assert.equal(numbers.isCloseTo("10", 10, 1), false);
  assert.equal(numbers.isCloseTo(10, "10", 1), false);
  assert.equal(numbers.isCloseTo(10, 10, "1"), false);
  assert.equal(numbers.isCloseTo(null, 10, 1), false);
  assert.equal(numbers.isCloseTo(10, null, 1), false);
  assert.equal(numbers.isCloseTo(10, 10, null), false);
  assert.equal(numbers.isCloseTo(undefined, 10, 1), false);
  assert.equal(numbers.isCloseTo(NaN, 10, 1), false);
  assert.equal(numbers.isCloseTo(10, NaN, 1), false);
  assert.equal(numbers.isCloseTo(10, 10, NaN), false);
  assert.equal(numbers.isCloseTo(Infinity, 10, 1), false);
  assert.equal(numbers.isCloseTo(10, -Infinity, 1), false);
  assert.equal(numbers.isCloseTo(10, 10, Infinity), false);
});

test("median", () => {
  assert.equal(numbers.median([1, 2, 3]), 2);
  assert.equal(numbers.median([3, 1, 2]), 2);
  assert.equal(numbers.median([1, 2, 3, 4]), 2.5);
  assert.equal(numbers.median([4, 1, 3, 2]), 2.5);
  assert.equal(numbers.median([-5, -1, -3]), -3);
  assert.equal(numbers.median([-2, 1, 4, 7]), 2.5);
  assert.equal(numbers.median([1.5, 2.5, 3.5]), 2.5);
  assert.equal(numbers.median([2, 2, 3, 4]), 2.5);
  assert.equal(numbers.median([7]), 7);
  assert.equal(Number.isNaN(numbers.median([])), true);
  assert.equal(Number.isNaN(numbers.median([1, "2", 3])), true);
  assert.equal(Number.isNaN(numbers.median([1, null, 3])), true);
  assert.equal(Number.isNaN(numbers.median([1, undefined, 3])), true);
  assert.equal(Number.isNaN(numbers.median([1, NaN, 3])), true);
  assert.equal(Number.isNaN(numbers.median([1, Infinity, 3])), true);
  assert.equal(Number.isNaN(numbers.median([1, -Infinity, 3])), true);
  assert.equal(Number.isNaN(numbers.median([1, true, 3])), true);
  assert.equal(Number.isNaN(numbers.median([1, {}, 3])), true);
  assert.equal(Number.isNaN(numbers.median(null)), true);
  assert.equal(Number.isNaN(numbers.median(undefined)), true);
  assert.equal(Number.isNaN(numbers.median("123")), true);
  assert.equal(Number.isNaN(numbers.median({})), true);
  assert.equal(Number.isNaN(numbers.median({ value: 1 })), true);
  assert.equal(Number.isNaN(numbers.median([, 2])), true);
  assert.equal(Number.isNaN(numbers.median([1, Symbol("2"), 3])), true);
});
